# How to manage *anchoring_detection* package

In [1]:
from anchoring_detection.preprocess import Preprocess
from anchoring_detection.analysis import Analysis
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import pandas as pd
import os

## Preparing the data

In [2]:
anchoring = Preprocess()

In [3]:
"""anchoring.work_definitions(aumentation='no')""" # The class add new simulations default. If you want to deprecate it, execute this line

"anchoring.work_definitions(aumentation='no')"

In [4]:
anchoring.extract_res_files() # Return a dictionary with all Dataframes for Surge and Sway

/home/arturo/Documentos/Mooring_anomaly_detector/anchoring_detection/preprocess.py:148: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col] - df[col].mean()

In [5]:
anchoring.dataframes_surge['oc4__Hs1__Tp2__dir3__1']

       time[s]     Surge
0        180.0 -1.479151
1        180.1 -1.476411
2        180.2 -1.473671
3        180.3 -1.470971
4        180.4 -1.468291
...        ...       ...
10196   1199.6  0.067959
10197   1199.7  0.064109
10198   1199.8  0.060319
10199   1199.9  0.056589
10200   1200.0  0.052949

[10201 rows x 2 columns]

## Build the different dataset options

### Time domain dataset

In [6]:
study = Analysis()

In [7]:
study.dataframe_for_analysis()

/home/arturo/Documentos/Mooring_anomaly_detector/anchoring_detection/analysis.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0,domain,df_domain)
/home/arturo/Documentos/Mooring_anomaly_detector/anchoring_detection/analysis.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0,domain,df_domain)

In [8]:
study.df_surge

,time[s],oc4__Hs1__Tp2__dir3__1.txt,oc4__Hs3__Tp5__dir1__3.txt,oc4__Hs1__Tp4__dir2__2.txt,oc4__Hs1__Tp5__dir1__1.txt,oc4__Hs1__Tp4__dir4__2.txt,oc4__Hs2__Tp4__dir1__3.txt,oc4__Hs1__Tp2__dir3__2.txt,oc4__Hs2__Tp5__dir4__2.txt,oc4__Hs3__Tp4__dir2__1.txt,...,oc4__Hs1__Tp2__dir2__2.txt,oc4__Hs2__Tp4__dir1__1.txt,oc4__Hs3__Tp5__dir1__1.txt,oc4__Hs1__Tp2__dir1__3.txt,oc4__Hs4__Tp5__dir1__3.txt,oc4__Hs1__Tp3__dir3__2.txt,oc4__Hs1__Tp2__dir5__2.txt,oc4__Hs2__Tp3__dir3__2.txt,oc4__Hs1__Tp5__dir1__4.txt,oc4__Hs3__Tp5__dir5__1.txt
0,180.0,-1.493449,-7.806978,-3.719421,-1.464663,-1.45896,-7.772465,-1.479151,-7.792413,-1.487987,...,-2.688311,-0.429013,-0.959113,-7.275642,-1.466601,-7.768536,-1.890862,-8.179824,-2.31354,-8.585323
1,180.1,-1.487229,-7.794478,-3.709361,-1.457283,-1.45465,-7.761865,-1.476411,-7.783313,-1.487917,...,-2.573781,-0.317093,-0.898053,-7.208442,-1.461601,-7.757236,-1.942172,-8.224724,-2.42752,-8.692723
2,180.2,-1.481179,-7.782078,-3.699481,-1.450083,-1.45049,-7.751365,-1.473671,-7.774313,-1.487807,...,-2.458101,-0.204013,-0.836813,-7.141042,-1.456951,-7.746336,-1.994352,-8.270524,-2.54246,-8.801023
3,180.3,-1.475329,-7.769978,-3.689811,-1.443093,-1.44652,-7.741065,-1.470971,-7.765313,-1.487647,...,-2.341401,-0.089913,-0.775443,-7.073542,-1.452661,-7.735736,-2.047332,-8.317024,-2.65822,-8.910123
4,180.4,-1.469719,-7.758078,-3.680381,-1.436343,-1.44272,-7.731065,-1.468291,-7.756313,-1.487427,...,-2.223801,0.025087,-0.714023,-7.005942,-1.448711,-7.725536,-2.101022,-8.364324,-2.77465,-9.019893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10196,1199.6,-0.061139,0.587722,0.073929,-0.075073,-0.00420,0.644635,0.067959,0.716687,0.143353,...,6.213419,6.087737,3.094427,3.710558,0.089769,0.729564,-2.892642,-2.249324,-5.81773,-5.190123
10197,1199.7,-0.056619,0.592322,0.078429,-0.070553,-0.00595,0.642935,0.064109,0.712887,0.137233,...,6.281219,6.155587,3.127207,3.743358,0.090729,0.730464,-2.924672,-2.281424,-5.87973,-5.252023
10198,1199.8,-0.051839,0.597022,0.083229,-0.065773,-0.00757,0.641335,0.060319,0.709087,0.131083,...,6.344219,6.218477,3.157277,3.773358,0.091349,0.730964,-2.954492,-2.311224,-5.93683,-5.309123
10199,1199.9,-0.046819,0.602122,0.088229,-0.060753,-0.00902,0.639835,0.056589,0.705387,0.124923,...,6.402119,6.276337,3.184617,3.800758,0.091639,0.731164,-2.982102,-2.338924,-5.98913,-5.361323
10200,1200.0,-0.041589,0.607322,0.093529,-0.055523,-0.01028,0.638635,0.052949,0.701787,0.118793,...,6.454919,6.329107,3.209197,3.825258,0.091589,0.731064,-3.007462,-2.364324,-6.03653,-5.408623

### Frequency domain dataset

In [9]:
anchoring.fourier() #FFT

In [10]:
study.dataframe_for_analysis(domain='Frequency')

/home/arturo/Documentos/Mooring_anomaly_detector/anchoring_detection/analysis.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0,domain,df_domain)
/home/arturo/Documentos/Mooring_anomaly_detector/anchoring_detection/analysis.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0,domain,df_domain)

In [11]:
study.df_surge

,Frequency,Frequencies,Amplitudes,Frequencies,Amplitudes,Frequencies,Amplitudes,Frequencies,Amplitudes,Frequencies,...,Frequencies,Amplitudes,Frequencies,Amplitudes,Frequencies,Amplitudes,Frequencies,Amplitudes,Frequencies,Amplitudes
0,0.000000,0.000000,1.354339e-16,0.000000,6.481326e-16,0.000000,4.513594e-16,0.000000,1.832777e-17,0.000000,...,0.000000,2.795224e-15,0.000000,2.304249e-16,0.000000,1.330396e-15,0.000000,5.837895e-16,0.000000,1.591599e-15
1,0.000980,0.000980,9.272685e-02,0.000980,6.962502e-01,0.000980,2.294697e-01,0.000980,7.787562e-02,0.000980,...,0.000980,6.869086e-01,0.000980,9.751848e-02,0.000980,6.952416e-01,0.000980,1.068736e-01,0.000980,6.968519e-01
2,0.001961,0.001961,1.090906e-01,0.001961,5.823722e-01,0.001961,2.278900e-01,0.001961,8.883191e-02,0.001961,...,0.001961,5.780568e-01,0.001961,1.106863e-01,0.001961,5.842543e-01,0.001961,1.191834e-01,0.001961,5.858313e-01
3,0.002941,0.002941,1.040265e-01,0.002941,4.422400e-01,0.002941,1.920874e-01,0.002941,7.709272e-02,0.002941,...,0.002941,4.406302e-01,0.002941,1.044966e-01,0.002941,4.440700e-01,0.002941,1.127674e-01,0.002941,4.418378e-01
4,0.003921,0.003921,8.015641e-02,0.003921,3.390597e-01,0.003921,1.535341e-01,0.003921,6.140394e-02,0.003921,...,0.003921,3.392178e-01,0.003921,8.651909e-02,0.003921,3.424643e-01,0.003921,9.156341e-02,0.003921,3.450002e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095,4.994608,4.994608,7.146223e-05,4.994608,4.130124e-04,4.994608,1.873669e-04,4.994608,6.937306e-05,4.994608,...,4.994608,4.165829e-04,4.994608,5.657862e-05,4.994608,2.833162e-04,4.994608,1.863202e-04,4.994608,1.516785e-04
5096,4.995589,4.995589,7.145788e-05,4.995589,4.125877e-04,4.995589,1.872773e-04,4.995589,6.939295e-05,4.995589,...,4.995589,4.166800e-04,4.995589,5.656370e-05,4.995589,2.830971e-04,4.995589,1.863318e-04,4.995589,1.519079e-04
5097,4.996569,4.996569,7.144889e-05,4.996569,4.127803e-04,4.996569,1.870715e-04,4.996569,6.937915e-05,4.996569,...,4.996569,4.169076e-04,4.996569,5.654711e-05,4.996569,2.835233e-04,4.996569,1.863843e-04,4.996569,1.519367e-04
5098,4.997549,4.997549,7.147529e-05,4.997549,4.127974e-04,4.997549,1.870496e-04,4.997549,6.936382e-05,4.997549,...,4.997549,4.168939e-04,4.997549,5.655389e-05,4.997549,2.830667e-04,4.997549,1.863778e-04,4.997549,1.520991e-04
5099,4.998530,4.998530,7.145586e-05,4.998530,4.131894e-04,4.998530,1.871214e-04,4.998530,6.935722e-05,4.998530,...,4.998530,4.168974e-04,4.998530,5.654967e-05,4.998530,2.834454e-04,4.998530,1.864154e-04,4.998530,1.520271e-04

### Spectral moment dataset

In [12]:
anchoring.moment_dataset() # Currently, the training models are using spectral moments, and that is the reason which the method save the data in .pkl file

                          Hs     Tp  Direction  m0_Surge   m0_Sway  Dragging
oc4__Hs1__Tp2__dir1__1  1.21   8.15          0  0.002438  0.001749         0
oc4__Hs1__Tp2__dir1__2  1.21   8.15          0  0.011784  0.008595         1
oc4__Hs1__Tp2__dir1__3  1.21   8.15          0  0.005411  0.005698         1
oc4__Hs1__Tp2__dir1__4  1.21   8.15          0  0.002285  0.003390         1
oc4__Hs1__Tp2__dir2__1  1.21   8.15         60  0.002250  0.001852         0
...                      ...    ...        ...       ...       ...       ...
oc4__Hs4__Tp5__dir3__2  8.10  18.69         90  0.012230  0.018121         1
oc4__Hs4__Tp5__dir4__1  8.10  18.69        120  0.005428  0.010878         0
oc4__Hs4__Tp5__dir4__2  8.10  18.69        120  0.012206  0.016706         1
oc4__Hs4__Tp5__dir5__1  8.10  18.69        180  0.011085  0.002734         0
oc4__Hs4__Tp5__dir5__2  8.10  18.69        180  0.013946  0.009060         1

[120 rows x 6 columns]